# Generated by Django 4.2.10 on 2024-03-17 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pomodoro_long_break_duration',
            field=models.IntegerField(default=15),
        ),
        migrations.AddField(
            model_name='user',
            name='pomodoro_session_duration',
            field=models.IntegerField(default=25),
        ),
        migrations.AddField(
            model_name='user',
            name='pomodoro_short_break_duration',
            field=models.IntegerField(default=5),
        ),
    ]
