# Generated by Django 4.2.10 on 2024-03-15 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_project_options_alter_task_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='task',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='task',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='task',
            name='updated_by',
        ),
    ]
