# Generated by Django 4.2.10 on 2024-03-15 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_remove_project_updated_by_remove_task_deleted_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='project',
            name='is_deleted',
        ),
    ]
