# Generated by Django 4.2.10 on 2024-03-15 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pomodoro', '0002_alter_pomodoro_options_alter_pomodorobreak_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pomodoro',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='pomodorobreak',
            name='updated_by',
        ),
    ]
