# Generated by Django 4.2.10 on 2024-03-16 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pomodoro', '0005_alter_pomodorosession_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pomodorosession',
            name='duration',
            field=models.DurationField(),
        ),
    ]
